name: 'Extract version commit'
description: 'Extracts the first commit matching the provided version_regex'
inputs:
  version_regex:
    description: |
      The version regex to use for detecting version in commit messages.
    required: false
    default: '([0-9]+\.[0-9]+\.[0-9]+)'

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'purple'
